-- CTAS
IF OBJECT_ID('Sales.MONTHLY_ORDERS','U') IS NOT NULL
DROP  TABLE Sales.MONTHLY_ORDERS 
GO
SELECT 
DATENAME(MONTH,OrderDate) OrderMonth,
COUNT(OrderID) TotalOrder
INTO Sales.MONTHLY_ORDERS
 FROM Sales.Orders GROUP BY DATENAME(MONTH,OrderDate)
 USE SalesDB