ALTER DATABASE SalesDB ADD FILEGROUP FG_2023
ALTER DATABASE SalesDB ADD FILEGROUP FG_2024
ALTER DATABASE SalesDB ADD FILEGROUP FG_2025
ALTER DATABASE SalesDB ADD FILEGROUP FG_2026

--- Remove Database ----
ALTER DATABASE SalesDB REMOVE FILEGROUP FG_2026

-- check DB --

select * from sys.filegroups where type='FG'