-- FIRST_VALUE()- FIRST ROW OF THE TABLE
-- LAST_VALUE() - LAST ROW OF THE TABLE
-- Default range - ROWS BETWEEN UNBOUNDED PRECEDING AND  CURRENT ROW
-- SO FOR LAST VALUE SET RNAGE FRMAE ONE WINDOW-
-- ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
SELECT
FIRST_VALUE(OrderDate) OVER(ORDER BY OrderDate),
LAST_VALUE(OrderDate) 
OVER(ORDER BY OrderDate ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING)
FROM
SalesDB.Sales.Orders

-- fIND THE LOWEST AND HIGHEST SALES OF EACH PRODUCT
SELECT
ProductID,
First_Value(Sales) OVER(PARTITION BY PRODUCTID Order By Sales Desc) HIGHEST_SALES_OF_PRODUCT,
Last_value(Sales) OVER(PARTITION BY PRODUCTID Order By Sales Desc
ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) LOWEST_SALES_OF_PRODUCT,
Sales-Last_value(Sales) OVER(PARTITION BY PRODUCTID Order By Sales Desc
ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS SalesDiff
fROM SalesDB.Sales.Orders